/* Generated by tools/build_calibration_notice.py; do not edit. */
self.UROSCalibration = Object.freeze({
  "presentation_version": "calibration-notice-1",
  "source": "core/redcf/stage_tree.json",
  "label": "存活率未校準",
  "note": "完工機率階段樹（DECISION_ENGINE_SPEC §2）。【部分校準】：duration_yr 之 T4–T7 已由一件在途真實案（案例E，防災都更2.0＋權變，本機 /local_calibration/）之官方時程錨定；p_survival 仍為【示意預設】，尚未經真實成敗案校準——單一在途案 n=1 無法產生頻率。故 verdict 仍為方向性判斷、非投資結論。",
  "calibration_status": {
    "_note": "誠實邊界：明列哪些欄位已錨定、哪些仍是假設。任何宣稱不得超出本表。",
    "anchor_case": "案例E（合成標籤；真實對照留 /local_calibration/，不進版控）",
    "anchor_state": "已送審議、尚未核定（在途）",
    "calibrated": [
      "duration_yr T4–T6（核定→開工 13 月）",
      "duration_yr T7（施工 35 月）",
      "核定→交屋合計 48 月（＝13＋35，官方預估）"
    ],
    "not_calibrated": [
      "p_survival 全部階段（需多案成敗頻率，非單一在途案可得）",
      "duration_yr T1–T3（本案 T1 已通過但未留完整耗時；T3 審議進行中，尚未定案）",
      "duration_yr T8（交屋結算落在 48 月之後，本案未達）"
    ],
    "conditional_note": "本案僅能支持【條件存活率】敘述（如：已過 T1 整合最大過濾器者，後續存活率區間），不得宣稱最終完工機率。",
    "observed": {
      "consent_ratio_at_review": 0.877,
      "_observed_note": "送審議時之同意比率（人數口徑）——證明 T1 可被通過，但 n=1 不足以估計 T1 存活率"
    }
  }
});
