/* apps/web/demo-case.js — B1.5 零步啟動：合成示範案（案例D，schema v2.1）預載記錄。
   AUTO-GENERATED by tools/build_demo_case.mjs — 勿手改。
   來源＝schemas/examples/v2/v2_1_案例D_權變示範.json（合成、零真實資料）＋ core/redcf decision.decide()。
   wf/snap 由 workspace WORKLOGIC 產出、engine 逐欄自 v2.1、decision 由決策引擎產出並經 schema 驗證。
   零公式、零推論——駕駛艙據此在無匯入時即有可操作案件（空狀態＝可運作狀態）。 */
self.DEMO_CASE = {
 "pid": "prj-737dbda4",
 "wf": {
  "schema_version": "wf-1.0",
  "project": {
   "project_id": "prj-737dbda4",
   "code_name": "案例D（權利變換示範）",
   "case_type": "danger_building",
   "mode": "合建",
   "stage": "S1",
   "active_snapshot": "snap-01",
   "snapshots": [
    {
     "id": "snap-01",
     "label": "匯入版",
     "schema_version": "2.1",
     "input_hash": "sha256:737dbda4cd7d863a6b4e00ecdf626c215d77ee6a08510d36a4720601a026e3be",
     "core_version": "0.3.0",
     "computed_at": "2026-07-01T00:00:00+00:00",
     "file_ref": "local:import"
    }
   ]
  },
  "stakeholders": [
   {
    "stakeholder_id": "W01",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 1276.17,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W02",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 1276.17,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W03",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 1276.17,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W04",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 1276.17,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W05",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W06",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W07",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W08",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W09",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W10",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W11",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W12",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W13",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W14",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W15",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W16",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W17",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W18",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W19",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W20",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W21",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W22",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W23",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W24",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W25",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W26",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W27",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W28",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W29",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W30",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W31",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W32",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W33",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W34",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:agreed"
    ]
   },
   {
    "stakeholder_id": "W35",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W36",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W37",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W38",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W39",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W40",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W41",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W42",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W43",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W44",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:pending"
    ]
   },
   {
    "stakeholder_id": "W45",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:opposed"
    ]
   },
   {
    "stakeholder_id": "W46",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:opposed"
    ]
   },
   {
    "stakeholder_id": "W47",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:opposed"
    ]
   },
   {
    "stakeholder_id": "W48",
    "role": "owner",
    "land_share": 0.020833,
    "pre_value": 708.98,
    "min_unit_eligible": true,
    "tags": [
     "consent:opposed"
    ]
   }
  ],
  "consent_events": [],
  "tasks": [],
  "decisions": []
 },
 "snap": {
  "code_name": "案例D（權利變換示範）",
  "case_type": "danger_building",
  "stakeholders_n": 48,
  "input_hash": "sha256:737dbda4cd7d863a6b4e00ecdf626c215d77ee6a08510d36a4720601a026e3be",
  "core_version": "0.3.0",
  "computed_at": "2026-07-01T00:00:00+00:00",
  "shared_cost_ratio": 0.66,
  "return_rate": 0.515,
  "warnings_n": 3,
  "agreed": 34,
  "total": 48,
  "threshold": 1,
  "allocations": [
   {
    "owner_id": "W01",
    "pre_value": 1276.17,
    "value_share": 0.035156,
    "return_value": 2702.12,
    "equalization": 97.88
   },
   {
    "owner_id": "W02",
    "pre_value": 1276.17,
    "value_share": 0.035156,
    "return_value": 2702.12,
    "equalization": -102.12
   },
   {
    "owner_id": "W03",
    "pre_value": 1276.17,
    "value_share": 0.035156,
    "return_value": 2702.12,
    "equalization": null
   },
   {
    "owner_id": "W04",
    "pre_value": 1276.17,
    "value_share": 0.035156,
    "return_value": 2702.12,
    "equalization": null
   },
   {
    "owner_id": "W05",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W06",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W07",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W08",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W09",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W10",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W11",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W12",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W13",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W14",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W15",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W16",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W17",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W18",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W19",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W20",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W21",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W22",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W23",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W24",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W25",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W26",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W27",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W28",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W29",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W30",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W31",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W32",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W33",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W34",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W35",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W36",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W37",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W38",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W39",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W40",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W41",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W42",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W43",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W44",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W45",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W46",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W47",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   },
   {
    "owner_id": "W48",
    "pre_value": 708.98,
    "value_share": 0.019531,
    "return_value": 1501.17,
    "equalization": null
   }
  ],
  "site": {
   "site_area_sqm": 1500,
   "plaza_area_sqm": 0,
   "far": 2.4,
   "bonus_ratio": 0.4,
   "tdr_transfer_sqm": 1080
  },
  "public_ratio": 0.34
 },
 "engine": {
  "params": {
   "案件名稱": "案例D（權利變換示範）",
   "基地面積": 1500,
   "人行廣場": 0,
   "容積率": 2.4,
   "獎勵率": 0.4,
   "容積移轉": 1080,
   "公設比": 0.34,
   "梯廳免計基準": 5,
   "陽台免計基準": 10,
   "面積表計入容積": 6120,
   "住宅單價": 65,
   "店舖坪數": 90,
   "店舖單價": 100,
   "車位數": 78,
   "車位單價": 230,
   "營造單價": 20,
   "戶數": 48,
   "權變戶數": 0,
   "土融土地成本": 50000,
   "地價": 80,
   "既有建物面積": 0,
   "建物單價": 0,
   "屋齡": 45,
   "財務覆寫": {
    "代銷費率": 0.06,
    "信託費率": 0.011
   }
  },
  "floors": [
   {
    "啟用": true,
    "樓層": "B1F",
    "樓板": 1300,
    "計容積": 0,
    "梯廳": 0,
    "安全梯": 0,
    "陽台": 0
   },
   {
    "啟用": true,
    "樓層": "B2F",
    "樓板": 1300,
    "計容積": 0,
    "梯廳": 0,
    "安全梯": 0,
    "陽台": 0
   },
   {
    "啟用": true,
    "樓層": "B3F",
    "樓板": 1300,
    "計容積": 0,
    "梯廳": 0,
    "安全梯": 0,
    "陽台": 0
   },
   {
    "啟用": true,
    "樓層": "1F",
    "樓板": 750,
    "計容積": 0,
    "梯廳": 75,
    "安全梯": 235,
    "陽台": 0
   },
   {
    "啟用": true,
    "樓層": "2F",
    "樓板": 430,
    "計容積": 0,
    "梯廳": 21.5,
    "安全梯": 178,
    "陽台": 43
   },
   {
    "啟用": true,
    "樓層": "3F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "4F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "5F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "6F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "7F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "8F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "9F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "10F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "11F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "12F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "13F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "14F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "15F",
    "樓板": 500,
    "計容積": 0,
    "梯廳": 25,
    "安全梯": 40,
    "陽台": 50
   },
   {
    "啟用": true,
    "樓層": "R1F",
    "樓板": 94,
    "計容積": 0,
    "梯廳": 0,
    "安全梯": 0,
    "陽台": 0
   }
  ],
  "case_type": "危老",
  "mode": "合建",
  "owners": [
   {
    "owner_id": "W01",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 1276.17,
    "consent": "agreed",
    "min_unit_eligible": true,
    "selected_value": 2800
   },
   {
    "owner_id": "W02",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 1276.17,
    "consent": "agreed",
    "min_unit_eligible": true,
    "selected_value": 2600
   },
   {
    "owner_id": "W03",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 1276.17,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W04",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 1276.17,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W05",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W06",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W07",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W08",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W09",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W10",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W11",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W12",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W13",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W14",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W15",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W16",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W17",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W18",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W19",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W20",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W21",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W22",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W23",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W24",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W25",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W26",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W27",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W28",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W29",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W30",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W31",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W32",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W33",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W34",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "agreed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W35",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W36",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W37",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W38",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W39",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W40",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W41",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W42",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W43",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W44",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "pending",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W45",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "opposed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W46",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "opposed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W47",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "opposed",
    "min_unit_eligible": true
   },
   {
    "owner_id": "W48",
    "land_share": 0.020833,
    "pre_building_area_sqm": 0,
    "pre_value": 708.98,
    "consent": "opposed",
    "min_unit_eligible": true
   }
  ]
 },
 "decision": {
  "decision_engine_version": "0.1.0",
  "input_hash": "sha256:737dbda4cd7d863a6b4e00ecdf626c215d77ee6a08510d36a4720601a026e3be",
  "verdict": "STOP",
  "breakpoint_stakeholder": "地主",
  "completion_probability": 0.2667,
  "T_remaining_yr": 10.8,
  "ev": {
   "地主": {
    "nominal": 40570.46,
    "ev": -15695.23,
    "status": "ok"
   },
   "實施者": {
    "nominal": -36000,
    "ev": -41758.19,
    "status": "ok"
   },
   "我方": {
    "nominal": 4800,
    "ev": -27.06,
    "status": "ok"
   }
  },
  "exit_signal": false,
  "sunk_cost_excluded": true,
  "decision_urgency": 0.5529,
  "assumptions": {
   "r": 0.06,
   "g": 0.03,
   "status_quo_baseline": "v0*(1+g)^T*df",
   "p_haircut": 0.9
  },
  "modeling_assumption": "status_quo_baseline",
  "insufficient_fields": []
 }
};
