import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
let passed=0;
const check=(name,fn)=>{fn();passed++;};
const root={};
const src=name=>readFileSync(new URL('../../apps/web/'+name,import.meta.url),'utf8');
for(const file of ['security.js','case-bus.js','massing-view.js','planning-session.js','site-massing.js','product-planning.js'])new Function('self',src(file))(root);
const engine=root.CaseBus.buildEngine(root.CaseBus.defaults());
const hash='sha256:'+'a'.repeat(64);
const base=root.CaseBus.buildRecord({engine,input_hash:hash,result:{core_version:'0.6.0',allow_floor_area:17}});
const answer={input_hash:'sha256:'+'b'.repeat(64),result:{core_version:'0.6.0',allow_floor_area:19,remaining_floor_area:-7}};
const prior=structuredClone(base);prior.cashflow={periods:[123]};prior.snap.allocations=[{owner_id:'old',return_value:99}];
const fresh=root.CaseBus.applyResult(prior,{engine,result:answer.result,input_hash:answer.input_hash});
check('new snapshot cannot reuse old cashflow',()=>assert.equal(fresh.cashflow,null));
check('missing new allocations stay empty, not old',()=>assert.deepEqual(fresh.snap.allocations,[]));
const alloc=[{owner_id:'synthetic',return_value:17}];
check('allocation is copied verbatim from new Core result',()=>assert.deepEqual(root.CaseBus.applyResult(prior,{engine,input_hash:hash,result:{...answer.result,owner_allocations:alloc}}).snap.allocations,alloc));
prior.wf.project.snapshots.push({id:'snap-02',input_hash:'old'});prior.wf.project.active_snapshot='snap-02';
const active=root.CaseBus.applyResult(prior,{engine,input_hash:answer.input_hash,result:answer.result});
check('only active workflow snapshot is replaced',()=>{assert.equal(active.wf.project.snapshots[1].input_hash,answer.input_hash);assert.equal(active.wf.project.snapshots[0].input_hash,hash);});
const overridden=structuredClone(engine);overridden.params.財務覆寫={住宅單價:123,公設比:0.88};
check('financial input follows existing effective override',()=>assert.equal(root.ProductPlanning.inputTarget(overridden,'住宅單價').住宅單價,123));
check('public ratio remains capacity input, not financial override',()=>assert.equal(root.ProductPlanning.inputTarget(overridden,'公設比'),overridden.params));
let stored=structuredClone(base),writes=0;
root.CaseBus.activeRecord=()=>structuredClone(stored);
root.CaseBus.replace=(pid,rec)=>{writes++;stored=structuredClone(rec);};
const make=(rt)=>root.PlanningSession.create(base,()=>rt,()=>{});
let session=make({ready:true,recompute:async()=>answer});
check('cannot accept uncomputed draft',()=>assert.throws(()=>session.accept()));
await session.run();
check('output is verbatim Core response',()=>assert.deepEqual(session.state().response,answer));
check('preview does not persist',()=>assert.equal(writes,0));
const edited=structuredClone(engine);edited.params.住宅單價=99;
session.update(edited);
check('input edit immediately invalidates output',()=>assert.equal(session.state().response,null));
check('stale output cannot be accepted',()=>assert.throws(()=>session.accept()));
await session.run();stored.wf.tasks.push({task_id:'concurrent',title:'New task'});
session.accept();
check('explicit accept writes once',()=>assert.equal(writes,1));
check('stable project id retained',()=>assert.equal(stored.pid,base.pid));
check('fresh workflow facts preserved',()=>assert.equal(stored.wf.tasks[0].task_id,'concurrent'));
check('adopted engine exact',()=>assert.deepEqual(stored.engine,edited));
check('adoption clears leave warning',()=>assert.equal(session.state().dirty,false));
session.dispose();
const legacy=structuredClone(base);delete legacy.pid;stored=structuredClone(base);
session=root.PlanningSession.create(legacy,()=>({ready:true,recompute:async()=>answer}),()=>{});await session.run();
check('legacy record without redundant pid can be adopted',()=>assert.equal(session.accept().pid,base.pid));session.dispose();
for(const conflict of ['engine','hash','pid']){
  stored=structuredClone(base);session=make({ready:true,recompute:async()=>answer});await session.run();
  if(conflict==='engine')stored.engine.params.住宅單價=100;
  if(conflict==='hash')stored.snap.input_hash='changed';
  if(conflict==='pid')stored.pid='other-case';
  check('concurrent '+conflict+' change rejected',()=>assert.throws(()=>session.accept(),/其他頁面/));session.dispose();
}
stored=structuredClone(base);let finish;
session=make({ready:true,recompute:()=>new Promise(r=>finish=r)});
const pending=session.run();session.update(edited);finish(answer);await pending;
check('late response cannot revive an invalidated draft',()=>assert.equal(session.state().response,null));session.dispose();
session=make({ready:true,recompute:async()=>answer});session.update(engine,false);await session.run();
check('invalid input cannot compute',()=>assert.equal(session.state().phase,'invalid'));session.dispose();
session=make({ready:true,recompute:async()=>{throw Error('Failed importScripts secret');}});await session.run();
check('raw error not exposed',()=>assert.ok(!session.state().message.includes('importScripts')));session.dispose();
session=make({failed:true});await session.run();
check('unavailable Core is terminal error',()=>assert.equal(session.state().phase,'error'));session.dispose();
session=make({ready:true,recompute:async()=>({result:{}})});await session.run();
check('missing provenance rejected',()=>assert.equal(session.state().phase,'error'));session.dispose();
stored=structuredClone(base);session=make({ready:true,recompute:async()=>answer});await session.run();
root.CaseBus.replace=()=>{throw Error('QuotaExceededError');};
check('storage failure cannot report adopted',()=>assert.throws(()=>session.accept()));session.dispose();
check('storage failure shown without raw exception',()=>assert.ok(!root.PlanningSession.saveError(Error('QuotaExceededError: private data')).includes('private')));
let scheduledCalls=0;session=make({ready:true,recompute:async()=>{scheduledCalls++;return answer;}});session.schedule(10);session.cancelScheduled();await new Promise(r=>setTimeout(r,25));
check('turning automatic calculation off cancels queued work',()=>assert.equal(scheduledCalls,0));session.dispose();
const before=[{樓層:'1F',樓板:200,啟用:true}],after=[{樓層:'1F',樓板:400,啟用:true},{樓層:'2F',樓板:400,啟用:false}];
const graphic=root.SiteMassing.comparison(before,after,0,false);
const widths=[...graphic.matchAll(/width="([\d.]+)" height="18"/g)].map(m=>Number(m[1]));
check('shared scale makes doubled plate visibly double',()=>assert.deepEqual(widths,[153,306,306]));
check('disabled floor remains visible',()=>assert.match(graphic,/sm-disabled/));
check('only draft diagram is selectable',()=>assert.equal((graphic.match(/data-mv-row=/g)||[]).length,2));
const hostile=root.SiteMassing.comparison([],[{樓層:'<img src=x onerror=alert(1)>',樓板:10}],0,false);
check('floor names escaped',()=>assert.ok(!hostile.includes('<img')));
check('diagram has no output drag path',()=>assert.ok(!/dragstart|dragover|draggable\s*=|pointermove/.test(src('site-massing.js'))));
check('adoption is separate from visual module',()=>assert.ok(!/CaseBus\.(replace|upsert)/.test(src('site-massing.js'))));
console.log(`PLANNING SESSION: ${passed} passed`);
