import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import Dashboard from '../../apps/web/executive-dashboard.js';

const rec={snap:{computed_at:'2026-10-01',input_hash:'current',core_version:'0.6.0'},engine:{params:{}},wf:{project:{snapshots:[{id:'old',computed_at:'2026-06-01',input_hash:'old'}]}}};
const scenarios=[{scenario_id:'s1',created_at:'2026-07-01',name:'合成方案',input_hash:'old',engine:{params:{住宅單價:60}}}];
const creation={kind:'scenario',field:'created',after:true,target:{id:'s1'},ts:'2026-07-01',key:'create'};
const adoption={kind:'scenario',field:'authoritative',after:true,target:{id:'s1'},ts:'2026-09-01',key:'adopt'};
assert.equal(Dashboard.sources(rec,scenarios,[creation],'adopted').length,2);
const applied=Dashboard.sources(rec,scenarios,[creation,adoption],'adopted');
assert.equal(applied.length,3);
assert.equal(applied.find(p=>p.source==='adoption').ts,adoption.ts);
assert.equal(applied.find(p=>p.source==='snapshot'&&p.source_id==='old').engine,scenarios[0].engine);
assert.equal(Dashboard.sources(rec,scenarios,[],'scenarios')[0].ts,scenarios[0].created_at);
assert.equal(Dashboard.sources(rec,[],[adoption],'adopted').find(p=>p.source==='adoption').engine,null);
const before=JSON.stringify({rec,scenarios,creation,adoption});
Dashboard.sources(rec,scenarios,[creation,adoption],'adopted');
assert.equal(JSON.stringify({rec,scenarios,creation,adoption}),before);
const html=readFileSync(new URL('../../apps/web/executive-dashboard.html',import.meta.url),'utf8');
const js=readFileSync(new URL('../../apps/web/executive-dashboard.js',import.meta.url),'utf8');
assert.doesNotMatch(html,/three|spatial-stage|type="number"|iframe|canvas/i);
assert.match(html,/type="date"/);
assert.match(js,/runtime\.dashboard/);
assert.doesNotMatch(js,/CaseStore\.(?:add|put|save|append|set|delete)|bus\.(?:replace|upsert|writeStore)|localStorage\.setItem/);
assert.doesNotMatch(js,/report\.deltas\[[^\]]+\]\s*=|shared_cost\s*[-+*/]/);
assert.match(js,/stored-snapshot/);
assert.match(js,/timeZone:'Asia\/Taipei'/);
const product=readFileSync(new URL('../../apps/web/product-planning.js',import.meta.url),'utf8');
assert.ok(js.includes('evaluator.html#scenario-comparison')&&product.includes('id="scenario-comparison"'));
console.log('EXECUTIVE DASHBOARD: 15 source/read-only boundary assertions passed');
