import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = file => readFileSync(new URL("../../" + file, import.meta.url), "utf8");
const values = new Map(), storage = { getItem: k => values.get(k) ?? null, setItem: (k,v) => values.set(k,String(v)), removeItem: k => values.delete(k), key: i => [...values.keys()][i], get length(){return values.size;} };
const root = {}, doc = { readyState: "loading", addEventListener(){} };
new Function("self", read("apps/web/security.js"))(root);
new Function("self","localStorage", read("apps/web/case-drafts.js"))(root,storage);
new Function("self","document","localStorage",read("apps/web/browser-backup.js"))(root,doc,storage);
let count=0;
function test(name,fn){fn();count++;console.log("PASS",name);}
const D=root.CaseDrafts, B=root.BrowserBackup;
test("intent isolated by project",()=>{D.set("A","intent","alpha");D.set("B","intent","beta");assert.equal(D.get("A","intent"),"alpha");assert.equal(D.get("B","intent"),"beta");});
test("visited flags isolated",()=>{D.set("A","site_visited",true);assert.equal(D.get("B","site_visited"),undefined);});
test("global intent retained, never silently adopted",()=>{storage.setItem("uros.intent","legacy");assert.equal(D.legacyIntent(),"legacy");assert.equal(D.get("C","intent"),undefined);});
test("draft version enforced",()=>{storage.setItem("uros.case-drafts.v1.X",JSON.stringify({version:2,project_id:"X",values:{}}));assert.throws(()=>D.read("X"));});
test("draft project binding enforced",()=>{storage.setItem("uros.case-drafts.v1.X",JSON.stringify({version:1,project_id:"Y",values:{}}));assert.throws(()=>D.read("X"));});
test("inference fields cannot be saved as drafts",()=>{D.set("A","verdict","GO");assert.equal(D.get("A","verdict"),undefined);});
const now=Date.parse("2026-09-10T00:00:00Z");
for(const value of [null,"invalid","2027-01-01"]){test("invalid backup timestamp remains due: "+value,()=>assert.equal(B.statusText(value,now).due,true));}
test("seven-day threshold inclusive",()=>assert.equal(B.statusText("2026-09-03T00:00:00Z",now).due,true));
test("recent backup not overdue",()=>assert.equal(B.statusText("2026-09-09T00:00:00Z",now).due,false));
const envelope={format:"uros-browser-backup",version:1,local_storage:{"uros.theme":"light"},idb:{format:"uros-backup",version:1,cases:[],activity:[],meta:[]}};
test("versioned empty backup valid",()=>assert.equal(B.validate(envelope),envelope));
test("unknown backup version refused",()=>assert.throws(()=>B.validate({...envelope,version:2})));
test("non-app storage keys refused",()=>assert.throws(()=>B.validate({...envelope,local_storage:{token:"secret"}})));
test("duplicate event keys refused",()=>assert.throws(()=>B.validate({...envelope,idb:{...envelope.idb,activity:[{key:1},{key:1}]}})));
test("missing case index refused",()=>assert.throws(()=>B.validate({...envelope,local_storage:{"uros.workflow.v1":JSON.stringify({order:["missing"],projects:{}})}})));
test("all six entry surfaces expose backup and calibration",()=>{for(const file of ["index","dashboard","evaluator","os-simulator","report","workspace"]){const s=read("apps/web/"+file+".html");assert.ok(s.includes('src="browser-backup.js"'));assert.ok(s.includes('src="calibration-data.js"'));}});
new Function("self","module",read("apps/web/case-bus.js"))(root,{exports:{}});
test("owner cap explicitly reported and original roster retained",()=>{const rec={wf:{project:{project_id:"A"},stakeholders:Array.from({length:81},(_,i)=>({role:"owner",stakeholder_id:"O"+i}))},snap:{total:81}};const bridge=root.CaseBus.buildSandboxBridge(rec);assert.equal(bridge.owners,null);assert.equal(bridge.owners_count,81);assert.match(bridge.owners_notice,/81.*80/);assert.equal(rec.wf.stakeholders.length,81);});
test("runtime same-origin first and only 404 falls back",()=>{const s=read("apps/web/core-runtime.worker.js");assert.match(s,/let base = LOCAL/);assert.match(s,/probe.status === 404/);assert.match(s,/indexURL: base/);});
test("no premature backup stamp",()=>{const s=read("apps/web/browser-backup.js");assert.match(s,/await stream.close\(\); await confirmed\(\)/);assert.ok(!read("apps/web/dashboard.html").includes("CS.markBackedUp()"));});
test("single manual creation surface",()=>assert.ok(!read("apps/web/dashboard.html").includes("function submitNewCase")));
root.addEventListener=()=>{};
new Function("self","localStorage",read("apps/web/local-diagnostics.js"))(root,storage);
test("diagnostics bounded to fifty events",()=>{for(let i=0;i<60;i++)root.UROSDiagnostics.record('core-unavailable');assert.equal(root.UROSDiagnostics.read().length,50);});
test("diagnostics reject arbitrary messages",()=>{root.UROSDiagnostics.record('private case input');assert.ok(root.UROSDiagnostics.read().every(e=>Object.keys(e).sort().join(',')==='at,code'));});
test("diagnostics never call a remote service",()=>assert.ok(!/fetch\(|XMLHttpRequest|sendBeacon|WebSocket/.test(read('apps/web/local-diagnostics.js'))));
console.log(`PLAYER FEEDBACK: ${count} passed`);
