import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=f=>readFileSync(new URL('../../'+f,import.meta.url),'utf8');
const root={};
for(const f of ['security.js','case-bus.js','site-intake.js','planning-session.js','product-planning.js','strategy-workspace.js'])new Function('self',read('apps/web/'+f))(root);
const workflow=new Function(read('apps/web/workflow-logic.js')+';return WORKLOGIC;')();
let passed=0;
const test=(name,fn)=>{fn();passed++;};
const I=root.SiteIntake, B=root.CaseBus;
const doc=I.empty('synthetic');
doc.parcels=[{id:'p-test',label:'Test',points:[[.1,.1],[.8,.1],[.5,.8]]}];
test('sketch preserves user vertices without derived area',()=>assert.deepEqual(I.validate(doc,'synthetic'),doc));
test('other case cannot consume sketch',()=>assert.throws(()=>I.validate(doc,'other')));
test('unknown version fails closed',()=>assert.throws(()=>I.validate({...doc,schema_version:'0'},'synthetic')));
test('not accepted as measured geometry',()=>assert.throws(()=>I.validate({...doc,coordinate_space:'EPSG:3826'},'synthetic')));
test('bounded parcels',()=>assert.throws(()=>I.validate({...doc,parcels:Array(9).fill(doc.parcels[0])},'synthetic')));
test('bounded vertices',()=>assert.throws(()=>I.validate({...doc,parcels:[{...doc.parcels[0],points:Array(65).fill([.1,.1])}]},'synthetic')));
test('duplicate parcel ids rejected',()=>assert.throws(()=>I.validate({...doc,parcels:[doc.parcels[0],doc.parcels[0]]},'synthetic')));
for(const point of [[NaN,.1],[1.1,.1],['.1',.1]])test('invalid point rejected '+point,()=>assert.throws(()=>I.validate({...doc,parcels:[{...doc.parcels[0],points:[point]}]},'synthetic')));
test('unknown fields rejected',()=>assert.throws(()=>I.validate({...doc,land:{owners:'private'}},'synthetic')));
test('invalid coverage rejected',()=>assert.throws(()=>I.validate({...doc,land:{coverage_percent:101}},'synthetic')));
test('land arrays rejected',()=>assert.throws(()=>I.validate({...doc,land:[]},'synthetic')));
test('intake never requests external service or computes cadastral area',()=>assert.doesNotMatch(read('apps/web/site-intake.js'),/fetch\(|XMLHttpRequest|shoelace|measured_area/));
const hash='sha256:'+'a'.repeat(64),engine=B.buildEngine(B.defaults());
const flow={schema_version:'cashflow-view-0.1',basis:'cost-disbursement-only',input_hash:hash,core_version:'0.6.0',科目:{A:56},期別出資:Array(8).fill(7),累積:[7,14,21,28,35,42,49,56],峰值資金:56,期數:8,structural:true};
const rec=B.buildRecord({engine,input_hash:hash,result:{core_version:'0.6.0',owner_allocations:[{owner_id:'W1',return_value:7}]},cashflow:flow});
test('new case carries bound Core flow',()=>assert.deepEqual(rec.cashflow,flow));
test('new case carries household outputs',()=>assert.equal(rec.snap.allocations.length,1));
test('changed identity cannot display old flow',()=>assert.equal(B.boundCashflow(flow,'other','0.6.0'),null));
test('cross-version flow rejected',()=>assert.equal(B.boundCashflow(flow,hash,'0.7.0'),null));
test('malformed imported flow cannot break the view',()=>assert.equal(B.boundCashflow({...flow,累積:null},hash,'0.6.0'),null));
test('non-finite flow cannot be displayed',()=>assert.equal(B.boundCashflow({...flow,科目:{A:Infinity}},hash,'0.6.0'),null));
rec.site_intake=doc;
const next=B.applyResult(rec,{engine,input_hash:hash,result:{core_version:'0.6.0'},cashflow:flow});
test('adopting result preserves local site facts',()=>assert.deepEqual(next.site_intake,doc));
test('disbursement disclosure not net cashflow',()=>assert.match(root.ProductPlanning.cashflowHTML(flow),/不是淨資金缺口/));
engine.params.財務覆寫={土地成本:15};
test('land-cost control writes effective override',()=>assert.equal(root.ProductPlanning.inputKey(engine,'土融土地成本'),'土地成本'));
test('land-cost control reads effective override',()=>assert.equal(root.ProductPlanning.inputTarget(engine,'土融土地成本').土地成本,15));
rec.wf.stakeholders=[{stakeholder_id:'W1',role:'owner',tags:['consent:agreed']},{stakeholder_id:'W2',role:'owner'}];
rec.wf.consent_events=[{stakeholder_id:'W1',kind:'withdrawn',ts:'2026-01-01'},{stakeholder_id:'W2',kind:'signed',ts:'2026-01-02'}];
test('consent events update displayed count',()=>assert.equal(B.consentFacts(rec).agreed,1));
test('sandbox reflects withdrawal',()=>assert.equal(B.buildSandboxBridge(rec).owners[0].consent,'pending'));
test('sandbox reflects latest signature',()=>assert.equal(B.buildSandboxBridge(rec).owners[1].consent,'agreed'));
test('factual board and cross-step counts agree',()=>assert.equal(workflow.consentBoard(rec.wf).tally.agreed_unselected,B.consentFacts(rec).agreed));
test('imported per-owner consent is preserved on factual board',()=>assert.equal(workflow.consentBoard({...rec.wf,consent_events:[]}).tally.agreed_unselected,1));
test('strategy invalidates on event change',()=>{const copy=structuredClone(rec);copy.wf.consent_events.push({kind:'contacted'});assert.notEqual(root.StrategyWorkspace.sourceKey(rec),root.StrategyWorkspace.sourceKey(copy));});
const html=read('apps/web/os-simulator.html');
const sim=new Function(html.split('/*SIMCORE-BEGIN*/')[1].split('/*SIMCORE-END*/')[0]+';return SIMCORE;')();
const s=sim.create({N:48,consent:20,seed:123});
test('weekly actions increased to eight',()=>assert.equal(s.ap,8));
const pending=Object.values(s.units).filter(u=>u.consent==='pending');
test('roles have diverse opening dialogue',()=>assert.ok(new Set(pending.slice(0,10).map(u=>sim.dialogue(s,u.id))).size>=8));
test('dialogue is deterministic',()=>assert.equal(sim.dialogue(s,pending[0].id),sim.dialogue(s,pending[0].id)));
test('listening changes context',()=>{const id=pending[0].id,old=sim.dialogue(s,id);sim.listen(s,id);assert.notEqual(old,sim.dialogue(s,id,'listen'));});
test('offers differ from listening',()=>assert.notEqual(sim.dialogue(s,pending[0].id,'offer'),sim.dialogue(s,pending[0].id,'listen')));
test('turn resets eight actions',()=>{sim.endWeek(s);assert.equal(s.ap,8);});
test('dialogue disclosed as simulation',()=>assert.match(html,/模擬對話.*非訪談紀錄/));
test('home discards late Core responses',()=>assert.match(read('apps/web/index.html'),/if\(token!==輸入序\)/));
test('Product studio stylesheet wins over the legacy shell',()=>{const p=read('apps/web/evaluator.html');assert.ok(p.indexOf('href="builder-studio.css"')>p.indexOf('href="os-unified.css"'));});
test('mobile navigation uses separate collapse and expand thresholds',()=>assert.match(read('apps/web/stepnav.js'),/\? 8 : 120/));
console.log(`Development intake: ${passed} passed`);
