import {chromium} from "playwright";
import {spawnSync} from "node:child_process";
import {createServer} from "node:http";
import {readFileSync,existsSync,statSync} from "node:fs";
import {resolve,sep,extname} from "node:path";
import {fileURLToPath} from "node:url";
import assert from "node:assert/strict";

const root=fileURLToPath(new URL("../../",import.meta.url)),output=resolve(root,"tools/browser/artifacts/pages-"+Date.now());
let server,browser,base=process.env.BUILDER_PUBLIC_URL,passed=0;
if(!base){
  const built=spawnSync(process.env.PYTHON||"python",["tools/build_pages.py","--output",output],{cwd:root,encoding:"utf8"});
  assert.equal(built.status,0,built.stdout+built.stderr);
  const types={".html":"text/html; charset=utf-8",".js":"text/javascript",".mjs":"text/javascript",".json":"application/json",".css":"text/css"};
  server=createServer((req,res)=>{
    const pathname=decodeURIComponent(new URL(req.url,"http://localhost").pathname);
    if(!pathname.startsWith("/BUILDER/")){res.writeHead(404);res.end();return;}
    const file=resolve(output,pathname.slice("/BUILDER/".length));
    if(!file.startsWith(output+sep)||!existsSync(file)||!statSync(file).isFile()){res.writeHead(404);res.end();return;}
    res.writeHead(200,{"Content-Type":types[extname(file)]||"application/octet-stream"});res.end(readFileSync(file));
  });
  await new Promise(r=>server.listen(0,"127.0.0.1",r));
  base=`http://127.0.0.1:${server.address().port}/BUILDER/`;
}
const check=(value,name)=>{assert.ok(value,name);passed++;console.log("PASS",name);};
try{
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_PATH}:{})});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),requests=[],errors=[];
  context.on("request",r=>requests.push(r.url()));page.on("pageerror",e=>errors.push(e.message));
  await context.route("**/*",r=>r.request().url().startsWith(base)?r.continue():r.abort());
  await page.goto(base+"spatial-prototype.html");await page.waitForFunction(()=>!!window.spatialDiagnostics,{},{timeout:30000});
  await page.waitForFunction(()=>{const p=spatialPixelCheck();return p.different>p.total*.025;},{},{timeout:10000});
  check((await page.evaluate(()=>spatialPixelCheck())).different>0,"Pages-prefix 3D canvas nonblank");
  check(await page.locator("#runtime").isHidden(),"public demo excludes local Core diagnostics");
  check(requests.every(r=>r.startsWith(base)),"all prototype requests stay within project prefix");
  check(errors.length===0,"no published-path script errors");
  await page.locator("#top").click();check((await page.evaluate(()=>spatialDiagnostics())).mode==="top","published top view");
  await page.locator('[data-object="demo-building"]').click();check(await page.locator("#height").innerText()==="26 m","published object selection");
  await page.locator("#iso").click();await page.screenshot({path:resolve(root,"tools/browser/artifacts/pages-desktop.png"),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"published mobile no overflow");
  check((await page.evaluate(()=>spatialPixelCheck())).different>0,"published mobile canvas nonblank");
  await page.screenshot({path:resolve(root,"tools/browser/artifacts/pages-mobile.png"),fullPage:true});
  const build=await (await context.request.get(base+"build-info.json")).json();
  check(/^[0-9a-f]{40}$/.test(build.commit),"published build has commit provenance");
  await page.setViewportSize({width:1440,height:1000});
  // A fresh browser has no case: enter through the visible synthetic-demo action.
  await page.goto(base+"index.html");
  check(await page.locator('#entry').isVisible()&&await page.locator('#pm-resume').isHidden(),'first visit starts with quick evaluation');
  await page.waitForFunction(()=>!document.getElementById('btn-go').disabled,{},{timeout:120000});
  if((await page.locator('#btn-go').innerText()).includes('快速評估')){
    await page.locator('#btn-go').click();
    check(await page.locator('#btn-go').innerText()==='儲存為案件 →'&&await page.evaluate(()=>!localStorage.getItem('uros.workflow.v1')),'quick evaluation shows Core result before creating a case');
  }else check((await page.locator('#btn-go').innerText()).includes('先儲存輸入'),'offline first visit explains input-only save');
  await page.locator('#btn-demo').click();
  await page.waitForURL(base+'dashboard.html');await page.locator("body.uros-unified").waitFor();
  check(await page.locator('html').getAttribute('data-theme')==='dark','new workspace defaults to dark');
  check(await page.locator('.stage-viewport [data-stage="name"]').count()===0,'case name stays outside the synthetic viewport');
  check(await page.locator('.stage-preview').innerText()==='0.7 Preview','prototype maturity is explicit without changing release');
  check(await page.locator('.stage-demo-label').evaluate(el=>{
    const luminance=color=>{const rgb=color.match(/[\d.]+/g).slice(0,3).map(v=>Number(v)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;};
    const fg=luminance(getComputedStyle(el).color),bg=luminance(getComputedStyle(el.closest('.stage-viewport')).backgroundColor);
    return (Math.max(fg,bg)+.05)/(Math.min(fg,bg)+.05)>=4.5;
  }),'non-case label maintains readable contrast');
  const frame=page.frameLocator('.spatial-stage iframe');
  await frame.locator('canvas').waitFor();
  check(await page.evaluate(()=>typeof window.spatialDiagnostics==='undefined'),"Three runtime remains in the child document");
  const storage=await page.evaluate(()=>JSON.stringify(Object.entries(localStorage)));
  await frame.locator('#top').click();
  check(await frame.locator('#top').getAttribute('aria-pressed')==='true',"in-workspace top view works");
  await frame.locator('#inspect').click();await frame.locator('[data-object="demo-building"]').click();
  check(await frame.locator('#height').innerText()==='26 m',"embedded source inspector retains explicit height");
  await frame.locator('#close-inspector').click();
  check(await frame.locator('#object-inspector').isHidden(),'source inspector has a visible close action');
  await frame.locator('#view-options > summary').click();await frame.locator('#focus').click();
  await frame.locator('#focus').press('Escape');
  check(await frame.locator('#view-options').getAttribute('open')===null,'advanced camera menu closes with Escape');
  check(await page.evaluate(()=>JSON.stringify(Object.entries(localStorage)))===storage,"embedded viewing never changes case storage");
  check(await page.locator('.stage-view-title').innerText().then(t=>t.includes('非本案量體')),"embedded model cannot be mistaken for the case geometry");
  await frame.locator('#iso').click();
  await page.screenshot({path:resolve(root,'tools/browser/artifacts/studio-desktop.png'),fullPage:false});
  await page.setViewportSize({width:390,height:844});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"embedded workspace mobile no overflow");
  await frame.locator('#top').click();
  check(await frame.locator('#top').getAttribute('aria-pressed')==='true',"embedded mobile camera control remains reachable");
  await page.screenshot({path:resolve(root,'tools/browser/artifacts/studio-mobile.png'),fullPage:false});
  await page.goto(base+'overview.html');
  check(await page.locator('#overview-case').isVisible()&&await page.locator('#overview-go').isVisible(),'published daily overview leads to the saved case next action');
  check(await page.locator('#data-status-rows tr').count()===9,'daily overview lists itemized Data Status without a synthetic score');
  check((await page.locator('#data-status-rows').innerText()).includes('原始來源未記錄'),'input values do not claim verified sources');
  check((await page.locator('#pulse-baseline').innerText()).includes('尚未設定比較基準'),'first Pulse visit does not invent a change baseline');
  await page.locator('#pulse-review').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('pulse-review').disabled);
  await page.locator('#pulse-review').click();
  check(await page.locator('#pulse-changes').innerText()==='0','explicit review starts a zero-change baseline');
  await page.goto(base+'os-simulator.html#workflow-task');
  await page.locator('#ttitle').fill('合成驗證任務');await page.locator('#towner').fill('驗證角色');await page.locator('#tdue').fill('2030-01-01');await page.locator('#taddbtn').click();
  const task=page.locator('.task-row').filter({hasText:'合成驗證任務'});
  await task.locator('.task-status').selectOption('blocked');await task.locator('.task-save').click();
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'task editor stays within mobile viewport');
  await page.screenshot({path:resolve(root,'tools/browser/artifacts/task-mobile.png'),fullPage:true});
  await page.waitForFunction(async()=>{const pid=CaseBus.activePid();return (await CaseStore.listActivity(pid)).some(ev=>ev.field&&ev.field.endsWith(':status')&&ev.after==='blocked');});
  await page.goto(base+'overview.html');
  check(Number(await page.locator('#pulse-changes').innerText())>=2,'Pulse shows recorded task changes after review');
  check((await page.locator('#pulse-blockers').innerText()).includes('合成驗證任務'),'Pulse lists an explicitly blocked task');
  check((await page.locator('#pulse-actions').innerText()).includes('驗證角色'),'next actions retain the manually assigned owner');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'published daily overview mobile no overflow');
  check(await page.evaluate(()=>['#pulse-review','#pulse-blockers a','#pulse-actions a'].every(selector=>{const el=document.querySelector(selector);return el&&el.getBoundingClientRect().height>=44;})),'Pulse mobile actions meet the 44px touch target');
  await page.goto(base+'meeting.html');
  check(await page.locator('#meeting-case').isVisible()&&(await page.locator('#meeting-name').innerText()).length>0,'meeting brief reads the active case');
  check((await page.locator('#meeting-blockers').innerText()).includes('合成驗證任務'),'meeting blockers come from recorded task status');
  await page.locator('#meeting-agenda-input').fill('合成待決策議題');
  check((await page.locator('#meeting-topics').innerText()).includes('合成待決策議題'),'meeting topics require explicit text');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'meeting brief mobile no overflow');
  await page.screenshot({path:resolve(root,'tools/browser/artifacts/meeting-mobile.png'),fullPage:true});
  await page.locator('#meeting-mark').click();
  check((await page.locator('#meeting-baseline').innerText()).includes('上次會議基準'),'meeting baseline is explicitly marked');
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:resolve(root,'tools/browser/artifacts/meeting-desktop.png'),fullPage:true});
  await page.emulateMedia({media:'print'});
  check(await page.locator('.meeting-toolbar').isHidden()&&await page.locator('#meeting-agenda-input').isHidden(),'meeting print layout omits editor controls');
  await page.emulateMedia({media:'screen'});
  await page.reload();
  check(await page.locator('#meeting-agenda-input').inputValue()==='合成待決策議題'&&(await page.locator('#meeting-baseline').innerText()).includes('上次會議基準'),'meeting draft and explicit baseline persist for this case');
  await page.screenshot({path:resolve(root,'tools/browser/artifacts/overview-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:resolve(root,'tools/browser/artifacts/overview-desktop.png'),fullPage:true});
  console.log(`PAGES: ${passed} passed; commit=${build.commit}`);
}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));}
