import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFileSync,existsSync,mkdirSync} from 'node:fs';
import {resolve,sep,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';

const root=fileURLToPath(new URL('../../',import.meta.url)),web=resolve(root,'apps/web'),artifacts=resolve(root,'tools/browser/artifacts');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.wasm':'application/wasm'};
const server=createServer((req,res)=>{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/BUILDER\//,'/');
  const base=pathname.startsWith('/runtime/')?artifacts:web,file=resolve(base,'.'+pathname);
  if(!file.startsWith(base+sep)||!existsSync(file)){res.writeHead(404);res.end();return;}
  res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});res.end(readFileSync(file));
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin='http://127.0.0.1:'+server.address().port;let browser,passed=0;
const check=(value,label)=>{assert.ok(value,label);passed++;console.log('PASS',label);};
const ready=page=>page.waitForFunction(()=>!document.querySelector('#btn-go').disabled&&document.querySelector('#ro-status').textContent.includes('就緒'),null,{timeout:150000});
const current=page=>page.locator('#entry-progress [aria-current="step"]').getAttribute('data-entry-step');
const contrast=page=>page.locator('#btn-go').evaluate(n=>{
  const style=getComputedStyle(n),luma=color=>{const v=color.match(/[\d.]+/g).slice(0,3).map(Number).map(c=>{c/=255;return c<=0.04045?c/12.92:((c+0.055)/1.055)**2.4;});return v[0]*0.2126+v[1]*0.7152+v[2]*0.0722;};
  const a=luma(style.color),b=luma(style.backgroundColor);return (Math.max(a,b)+0.05)/(Math.min(a,b)+0.05);
});
try{
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_PATH}:{})});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],external=[];
  await context.route('https://**',r=>{external.push(r.request().url());return r.fulfill({status:403,body:'blocked'});});
  page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message);});
  await page.goto(origin+'/BUILDER/index.html');
  check(await page.locator('#entry-progress').isVisible(),'first use shows the creation stepper');
  check(await current(page)==='1','first use starts at step 1');
  check((await page.locator('.entry-step-number').allTextContents()).join(',')==='1,2,3','three clear numeric creation steps');
  check(await page.locator('.brand svg').isVisible()&&await page.locator('a[href="executive-dashboard.html"] svg').isVisible(),'landing purpose icons rendered');
  check(await page.locator('#steps a').count()===0,'unsaved case cannot navigate into another active case');
  await ready(page);
  check(await current(page)==='1','Core readiness alone does not move the current step');
  check(await page.locator('#steps .home-icon').count()===4&&(await page.locator('#steps .sn').allTextContents()).join(',')==='1,2,3,4','four workflow stages have icons and large numbers');
  check(await page.evaluate(()=>CaseBus.readStore().order.length)===0,'preview creates no case');
  const initialStore=await page.evaluate(()=>localStorage.getItem(CaseBus.KEY));
  await page.locator('#btn-go').focus();await page.keyboard.press('Enter');
  check(await current(page)==='2','keyboard quick evaluation advances to step 2');
  check(await page.locator('#btn-go-label').innerText()==='儲存為案件 →','next action is explicitly save');
  check(await page.locator('#btn-go svg').isVisible(),'command icon survives label change');
  check(await page.evaluate(()=>localStorage.getItem(CaseBus.KEY))===initialStore,'review does not write a case');
  await page.locator('#f-基地面積').fill('850');
  check(await current(page)==='1','changing input returns to step 1 immediately');
  check(await page.locator('[data-entry-step="2"] .entry-step-status').innerText()==='尚未計算','changed input clears the old review status');
  await ready(page);await page.locator('#btn-go').click();
  check(await current(page)==='2','new Core result can be reviewed');
  await page.locator('#btn-reset').click();
  check(await current(page)==='1','reset returns to input without saving');
  await ready(page);
  mkdirSync(artifacts,{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:resolve(artifacts,'home-desktop.png'),fullPage:true});
  check(await contrast(page)>=4.5,'dark primary action has readable contrast');
  await page.screenshot({path:resolve(artifacts,'home-first-viewport.png')});
  await page.evaluate(()=>document.documentElement.setAttribute('data-theme','light'));
  await page.waitForTimeout(250);
  check(await page.locator('.brand svg').isVisible()&&await page.locator('#btn-go svg').isVisible(),'icons remain visible in the light theme');
  check(await contrast(page)>=4.5,'light primary action has readable contrast');
  await page.screenshot({path:resolve(artifacts,'home-light.png'),fullPage:true});
  await page.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));
  await page.waitForTimeout(250);
  for(const width of [390,320]){
    await page.setViewportSize({width,height:844});await page.evaluate(()=>scrollTo(0,0));
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'home fits mobile '+width);
    check(await page.locator('.entry-step-number').evaluateAll(ns=>ns.every(n=>n.getBoundingClientRect().width>=40&&n.getBoundingClientRect().height>=40)),'numeric steps remain prominent at '+width);
    check(await page.locator('.entry-step-label').evaluateAll(ns=>ns.every(n=>n.scrollWidth<=n.clientWidth)),'step labels fit at '+width);
    check(await page.locator('#btn-go').evaluate(n=>n.getBoundingClientRect().height>=44),'primary action touch target at '+width);
    await page.screenshot({path:resolve(artifacts,'home-mobile-'+width+'.png'),fullPage:true});
    await page.screenshot({path:resolve(artifacts,'home-first-viewport-'+width+'.png')});
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));
  await page.screenshot({path:resolve(artifacts,'home-dark.png'),fullPage:true});
  await page.locator('#btn-go').click();await page.locator('#btn-go').click();
  await page.waitForURL('**/BUILDER/dashboard.html');await page.waitForFunction(()=>typeof CaseBus!=='undefined'&&!!CaseBus.activeRecord());
  check(await page.evaluate(()=>CaseBus.readStore().order.length)===1,'explicit save creates exactly one case');
  const saved=await page.evaluate(()=>({pid:CaseBus.activePid(),store:localStorage.getItem(CaseBus.KEY)}));
  await page.screenshot({path:resolve(artifacts,'home-created-site.png'),fullPage:true});
  check(await page.locator('#site-massing-host').count()===1,'newly created case renders its Workspace');
  await page.getByRole('link',{name:'案件工作區',exact:true}).click();
  await page.getByRole('link',{name:'前往建立案件',exact:true}).click();await page.waitForURL('**/BUILDER/index.html?new=1#entry');
  check(await current(page)==='1'&&await page.locator('#entry-progress').isVisible(),'Workspace create link starts a new numbered flow');
  await page.goto(origin+'/BUILDER/index.html');
  check(await page.locator('#pm-resume').isVisible()&&await page.locator('#entry').isHidden(),'returning user sees resume, not onboarding');
  await page.locator('#edit-case').click();
  check(await page.locator('#entry-progress').isHidden(),'existing-case editing hides new-case steps');
  await page.locator('#new-case').click();
  check(await current(page)==='1'&&await page.locator('#entry-progress').isVisible(),'new case from resume resets the onboarding');
  check(await page.locator('#steps a').count()===0,'new draft cannot link to the previous case');
  check(await page.evaluate(()=>localStorage.getItem(CaseBus.KEY))===saved.store&&await page.evaluate(()=>CaseBus.activePid())===saved.pid,'new draft keeps the previous saved case intact');
  await ready(page);
  await page.locator('#f-基地面積').fill('1234');await ready(page);await page.locator('#btn-go').click();
  await page.evaluate(()=>{window.restoreStorageWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===CaseBus.KEY)throw new DOMException('Synthetic quota failure','QuotaExceededError');return window.restoreStorageWrite.call(this,k,v);};});
  await page.locator('#btn-go').click();
  check(page.url().includes('/index.html')&&await current(page)==='2','failed save remains on the reviewed draft');
  check(await page.locator('#f-基地面積').inputValue()==='1234'&&(await page.locator('#prov').innerText()).includes('輸入仍保留'),'failed save retains inputs and gives readable feedback');
  check(await page.evaluate(()=>localStorage.getItem(CaseBus.KEY))===saved.store,'failed save never overwrites the saved case');
  await page.evaluate(()=>{Storage.prototype.setItem=window.restoreStorageWrite;delete window.restoreStorageWrite;});
  await page.locator('#btn-go').click();await page.waitForURL('**/BUILDER/dashboard.html');await page.waitForFunction(()=>typeof CaseBus!=='undefined'&&CaseBus.readStore().order.length===2);
  check(await page.evaluate(()=>CaseBus.activePid())!==saved.pid,'explicit retry saves the new case independently');
  const firstCase=await page.evaluate(pid=>JSON.stringify(CaseBus.readStore().projects[pid]),saved.pid);
  await page.goto(origin+'/BUILDER/index.html?new=1#entry');await ready(page);await page.locator('#btn-go').click();await page.locator('#btn-go').click();await page.waitForURL('**/BUILDER/dashboard.html');await page.waitForFunction(()=>typeof CaseBus!=='undefined'&&CaseBus.readStore().order.length===3);
  check(await page.evaluate(pid=>CaseBus.activePid()!==pid&&CaseBus.activeRecord().snap.input_hash===CaseBus.readStore().projects[pid].snap.input_hash,saved.pid),'identical inputs create distinct case identities, not distinct calculation fingerprints');
  check(await page.evaluate(pid=>JSON.stringify(CaseBus.readStore().projects[pid]),saved.pid)===firstCase,'identical-input creation preserves the original case exactly');
  check(errors.length===0,'home flow has no unhandled browser errors');
  check(external.length===0,'local icons and runtime require no external request');
  await context.close();

  const offline=await browser.newContext({viewport:{width:390,height:844}}),down=await offline.newPage();
  await offline.addInitScript(()=>{window.Worker=class{constructor(){throw Error('Worker blocked');}};});
  await down.goto(origin+'/BUILDER/index.html');await down.waitForFunction(()=>!document.querySelector('#btn-go').disabled);
  check(await current(down)==='1'&&await down.locator('[data-entry-step="2"] .entry-step-status').innerText()==='尚未計算','Core failure never marks evaluation completed');
  check(await down.locator('[data-entry-step="3"] .entry-step-status').innerText()==='可先儲存輸入','offline flow visibly permits input-only save');
  await down.locator('#f-基地面積').fill('920');
  check((await down.locator('#btn-go').innerText()).includes('先儲存輸入'),'editing offline preserves the honest action label');
  check(await down.locator('#btn-go svg').isVisible(),'offline action retains its icon');
  await down.screenshot({path:resolve(artifacts,'home-offline.png'),fullPage:true});
  await down.evaluate(()=>{window.restoreStorageWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===CaseBus.KEY)throw new DOMException('Synthetic quota failure','QuotaExceededError');return window.restoreStorageWrite.call(this,k,v);};});
  await down.locator('#btn-go').click();
  check(await current(down)==='1'&&await down.locator('[data-entry-step="2"] .entry-step-status').innerText()==='尚未計算','failed input-only save does not invent a review');
  check(await down.locator('#btn-go-label').innerText()==='再試一次儲存 →','failed input-only save has an explicit retry action');
  await down.evaluate(()=>{Storage.prototype.setItem=window.restoreStorageWrite;delete window.restoreStorageWrite;});
  await down.locator('#btn-go').click();await down.waitForURL('**/BUILDER/dashboard.html');await down.waitForFunction(()=>typeof CaseBus!=='undefined'&&!!CaseBus.activeRecord());
  const pending=await down.evaluate(()=>CaseBus.activeRecord());
  check(pending.snap.input_hash.startsWith('pending:'),'input-only creation is not a fabricated Core snapshot');
  check(pending.engine.params.基地面積===920,'input-only save retains the entered fact');
  await down.goto(origin+'/BUILDER/index.html');await down.locator('#new-case').click();await down.locator('#btn-demo').click();await down.waitForURL('**/BUILDER/dashboard.html');await down.waitForFunction(()=>typeof CaseBus!=='undefined'&&!!CaseBus.activeRecord());
  check(await down.evaluate(pid=>{const s=CaseBus.readStore();return s.projects[pid]&&s.order.some(id=>s.projects[id].demo);},pending.pid),'explicit demo request preserves the user-created case');
  const missingDemo=await down.evaluate(()=>{const s=CaseBus.readStore(),id=s.order.find(p=>s.projects[p].demo);delete s.projects[id];s.order=s.order.filter(p=>p!==id);CaseBus.writeStore(s);localStorage.removeItem('uros.demo_seed_v');return id;});
  await down.reload();await down.waitForFunction(id=>typeof CaseBus!=='undefined'&&!!CaseBus.readStore().projects[id],missingDemo);
  check(await down.evaluate(pid=>CaseBus.readStore().projects[pid].snap.input_hash.startsWith('pending:'),pending.pid),'previously requested demo collection still upgrades without altering user cases');
  console.log('HOME BROWSER: '+passed+' passed');
}finally{await browser?.close();await new Promise(r=>server.close(r));}
