import {chromium} from "playwright";
import {spawn} from "node:child_process";
import {mkdirSync} from "node:fs";
import {fileURLToPath} from "node:url";
import {resolve} from "node:path";
import assert from "node:assert/strict";

const root=fileURLToPath(new URL("../../",import.meta.url)),artifacts=resolve(root,"tools/browser/artifacts");
mkdirSync(artifacts,{recursive:true});
const server=spawn(process.env.PYTHON||"python",["tools/serve_spatial_prototype.py","--port","0"],{cwd:root,env:{...process.env,PYTHONUNBUFFERED:"1"}});
let browser,passed=0,stderr="";server.stderr.on("data",x=>{stderr+=x;});
const origin=await new Promise((resolve,reject)=>{
  const timer=setTimeout(()=>{server.kill();reject(Error("Server timeout "+stderr));},15000);
  server.stdout.on("data",data=>{const match=String(data).match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});
  server.once("exit",code=>{clearTimeout(timer);reject(Error("Server exited "+code+stderr));});
});
function check(value,name){assert.ok(value,name);passed++;console.log("PASS",name);}
const state=page=>page.evaluate(()=>window.spatialDiagnostics());
try{
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),external=[],errors=[];
  context.on("request",req=>{if(!req.url().startsWith(origin))external.push(req.url());});
  await context.route("**/*",route=>route.request().url().startsWith(origin)?route.continue():route.abort());
  page.on("pageerror",e=>errors.push(e.message));
  await page.addInitScript(()=>{localStorage.setItem("lab-sentinel","unchanged");});
  const response=await page.goto(origin+"/");
  await page.waitForFunction(()=>!!window.spatialDiagnostics,{},{timeout:30000});
  check(response.headers()["content-security-policy"].includes("connect-src 'self'"),"same-origin CSP");
  check((await page.locator(".label").innerText()).includes("Synthetic"),"synthetic label persistent");
  check(await page.locator("#geometry-hash").innerText()!=="—","geometry hash present");
  const pixels=await page.evaluate(()=>spatialPixelCheck());
  check(pixels.different>pixels.total*.025,"desktop WebGL canvas contains visible geometry");
  const initial=await state(page);await page.locator("#top").click();
  check((await state(page)).mode==="top","top camera");
  await page.locator("#zoom-in").click();check((await state(page)).zoom>1,"zoom in");
  await page.locator("#zoom-out").click();check(Math.abs((await state(page)).zoom-1)<1e-9,"zoom out");
  await page.locator("#iso").click();
  const box=await page.locator("canvas").boundingBox(),x=box.x+box.width/2,y=box.y+box.height/2;
  await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+90,y+20,{steps:8});await page.mouse.up();
  check(JSON.stringify((await state(page)).position)!==JSON.stringify(initial.position),"drag rotates camera");
  await page.locator("#pan").click();const prePan=await state(page);
  await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+60,y+30,{steps:8});await page.mouse.up();
  check(JSON.stringify((await state(page)).target)!==JSON.stringify(prePan.target),"drag pans camera only");
  await page.locator("#reset").click();check((await state(page)).zoom===1,"reset camera");
  await page.locator("#top").click();await page.mouse.click(x,y);
  check((await state(page)).selected==="demo-building","raycast selects visible building");
  check(await page.locator("#height").innerText()==="26 m","selected height copied from fixture");
  await page.locator("#iso").click();await page.screenshot({path:resolve(artifacts,"spatial-desktop.png"),fullPage:true});
  await page.mouse.move(0,0);await page.waitForTimeout(250);const idle=await state(page);await page.waitForTimeout(250);
  check((await state(page)).renders===idle.renders,"idle viewer stops rendering");
  check(idle.drawCalls<=12&&idle.triangles<2000&&idle.pixelRatio<=1.5,"scene resource budget");
  await page.locator("#runtime > summary").click();await page.locator("#core-check").click();
  await page.waitForFunction(()=>document.querySelector("#core-status").textContent.includes("檢查通過"),{},{timeout:150000});
  check((await page.locator("#core-status").innerText()).includes("same-origin"),"real local Pyodide coexists with Three.js");
  check((await page.evaluate(()=>spatialPixelCheck())).different>0,"scene survives Core execution");
  check(await page.evaluate(()=>localStorage.length===1&&localStorage.getItem("lab-sentinel")==="unchanged"&&sessionStorage.length===0),"case storage remains untouched");
  check(external.length===0,"zero external browser requests");
  check(errors.length===0,"no desktop page errors");
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2}),mp=await mobile.newPage();
  await mp.goto(origin+"/");await mp.waitForFunction(()=>!!window.spatialDiagnostics);
  const mPixels=await mp.evaluate(()=>spatialPixelCheck());check(mPixels.different>mPixels.total*.025,"mobile canvas nonblank");
  check(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"mobile no horizontal overflow");
  check(await mp.locator("button").evaluateAll(nodes=>nodes.filter(n=>n.getClientRects().length).every(n=>n.getBoundingClientRect().height>=44)),"mobile touch targets");
  const cdp=await mobile.newCDPSession(mp),b=await mp.locator("canvas").boundingBox(),cx=b.x+b.width/2,cy=b.y+b.height/2;
  const touch=async(type,points)=>cdp.send("Input.dispatchTouchEvent",{type,touchPoints:points.map(([x,y],id)=>({x,y,id,radiusX:3,radiusY:3}))});
  const mInitial=await state(mp);await touch("touchStart",[[cx,cy]]);await touch("touchMove",[[cx+50,cy+20]]);await touch("touchEnd",[]);
  check(JSON.stringify((await state(mp)).position)!==JSON.stringify(mInitial.position),"one-finger rotate");
  const zoom=(await state(mp)).zoom;await touch("touchStart",[[cx-25,cy],[cx+25,cy]]);await touch("touchMove",[[cx-50,cy],[cx+50,cy]]);await touch("touchEnd",[]);
  check((await state(mp)).zoom!==zoom,"pinch zoom");
  const pan=(await state(mp)).target;await touch("touchStart",[[cx-25,cy],[cx+25,cy]]);await touch("touchMove",[[cx-5,cy+20],[cx+45,cy+20]]);await touch("touchEnd",[]);
  check(JSON.stringify((await state(mp)).target)!==JSON.stringify(pan),"two-finger pan");
  await mp.locator("#reset").tap();await mp.screenshot({path:resolve(artifacts,"spatial-mobile.png"),fullPage:true});
  const fallback=await browser.newContext();await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:original.call(this,type,...args);};});
  const fp=await fallback.newPage();await fp.goto(origin+"/");await fp.locator("#fallback").waitFor();
  check(await fp.locator("#zoom-in").isDisabled(),"WebGL unavailable disables camera tools");
  await fp.locator('[data-object="demo-building"]').click();check(await fp.locator("#height").innerText()==="26 m","WebGL fallback retains source data");
  await page.evaluate(()=>document.querySelector("canvas").getContext("webgl2").getExtension("WEBGL_lose_context").loseContext());
  await page.locator("#fallback").waitFor();check(await page.locator("#scene").isHidden(),"context loss has visible fallback");
  const missing=await browser.newContext();await missing.route("**/vendor/three.module.min.js",r=>r.fulfill({status:404,body:"missing"}));
  const np=await missing.newPage();await np.goto(origin+"/");await np.locator("#fallback").waitFor();check(await np.locator("#scene").isHidden(),"missing local dependency never falls back to CDN");
  console.log(`SPATIAL BROWSER: ${passed} passed`);
}finally{await browser?.close();server.kill();}
