"""Publish Core's calibration facts without modifying frozen decision outputs."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "apps/web/calibration-data.js"


def render():
    tree = json.loads((ROOT / "core/redcf/stage_tree.json").read_text(encoding="utf-8"))
    if not tree.get("_note") or not tree.get("calibration"):
        raise ValueError("Core calibration metadata is required")
    pending = tree["calibration"]["not_calibrated"]
    if not any("p_survival" in item for item in pending):
        raise ValueError("Calibration changed: review the presentation contract before publishing")
    data = {"presentation_version": "calibration-notice-1", "source": "core/redcf/stage_tree.json",
            "label": "存活率未校準", "note": tree["_note"], "calibration_status": tree["calibration"]}
    return "/* Generated by tools/build_calibration_notice.py; do not edit. */\n" + "self.UROSCalibration = Object.freeze(" + json.dumps(data, ensure_ascii=False, indent=2) + ");\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("Calibration presentation is out of sync with Core")
        print("PASS: calibration presentation matches Core metadata")
    else:
        TARGET.write_text(expected, encoding="utf-8", newline="\n")
