# -*- coding: utf-8 -*-
"""
tools/build_core_bundle.py — 打包 core/redcf 給瀏覽器內 Python（M5.5 B 軌・Pyodide）
====================================================================================
把「同一份」core/redcf 原始碼＋執行期資料檔，序列化成單一 classic JS
（apps/web/core-bundle.js），供 Web Worker 在 Pyodide FS 中還原目錄樹後 import。

SSOT 保衛：本檔＝**衍生產物**，來源永遠是 core/redcf。CI Gate 9 會重跑本工具並
`git diff --exit-code`——原始碼改了卻沒重建 bundle＝紅燈。故 bundle 不是第二真源，
是被守衛的鎖定產物（如 lockfile）。

排除 io.py / templates.py（依賴 pandas，僅 Streamlit 端用；瀏覽器計算主線純 stdlib）。
"""
import json
import hashlib
import pathlib

根 = pathlib.Path(__file__).resolve().parents[1]
OUT = 根 / "apps" / "web" / "core-bundle.js"

# 需還原到 Pyodide FS 的檔（相對 repo 根；路徑即 FS 內路徑 → parents[2] 解析與本機一致）
排除py = {"core/redcf/io.py", "core/redcf/templates.py"}


def 蒐集() -> dict:
    files = {}
    # 1) core 套件 .py（除 pandas 相依）
    for p in sorted((根 / "core").rglob("*.py")):
        rel = p.relative_to(根).as_posix()
        if rel in 排除py:
            continue
        files[rel] = p.read_text(encoding="utf-8")
    files.setdefault("core/__init__.py", "")   # 命名空間套件保險
    # 2) core 執行期資料檔
    for rel in ["core/redcf/stage_tree.json", "core/redcf/decision_config.json",
                "core/redcf/strategy_config.json"]:
        files[rel] = (根 / rel).read_text(encoding="utf-8")
    # 3) valuation 讀的係數檔（置於 apps/web）
    files["apps/web/coefficients.json"] = (根 / "apps/web/coefficients.json").read_text(encoding="utf-8")
    # 4) schemas（validator 讀取；全帶以自足）
    for p in sorted((根 / "schemas").glob("*.json")):
        files[p.relative_to(根).as_posix()] = p.read_text(encoding="utf-8")
    return files


def 建置() -> str:
    files = 蒐集()
    payload = {k: files[k] for k in sorted(files)}   # 排序＝可重現 diff
    canon = json.dumps(payload, ensure_ascii=False, sort_keys=True)
    ver = hashlib.sha256(canon.encode("utf-8")).hexdigest()[:16]
    body = json.dumps(payload, ensure_ascii=False, sort_keys=True, indent=1)
    return (
        "/* AUTO-GENERATED by tools/build_core_bundle.py — 勿手改。\n"
        "   來源＝core/redcf（SSOT）；CI Gate 9 以 git diff 守衛同步。 */\n"
        f'self.CORE_BUNDLE_VERSION = "{ver}";\n'
        f"self.CORE_FILES = {body};\n"
    )


def main() -> int:
    OUT.write_text(建置(), encoding="utf-8")
    n = len(蒐集())
    print(f"✅ 打包 {n} 檔 → {OUT.relative_to(根)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
