/* tools/build_demo_case.mjs — 生成 apps/web/demo-case.js（B1.5 零步啟動的合成示範案）
   ============================================================================
   來源＝schemas/examples/v2/v2_1_案例D_權變示範.json（合成、零真實資料）。
   步驟：
     1) 用 core/redcf decision.decide() 產出並驗證 decision JSON（Python 子行程；SSOT）。
     2) 抽出 workspace.html 的 WORKLOGIC 區塊，跑 importV21ToWorkflow + displaySnapshot 得 wf/snap。
     3) 組成 {pid, wf, snap, engine, decision} 寫入 apps/web/demo-case.js。
   demo-case.js＝被守衛的衍生產物（同 core-bundle.js 精神）：改 demo 請改來源 JSON 後重跑本工具。
   用法：node tools/build_demo_case.mjs
*/
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'schemas/examples/v2/v2_1_案例D_權變示範.json');
const v21 = JSON.parse(readFileSync(SRC, 'utf8'));

// ── 1) decision JSON（真 Core，全揭露的合成建模假設）──
const py = `
import json, sys
from core.redcf import decision as D
d = json.load(open(${JSON.stringify(SRC)}, encoding="utf-8"))
result = d["result"]; ih = d["provenance"]["input_hash"]
owners = d["input"]["owners"]
agreed = sum(1 for o in owners if o.get("consent") == "agreed")
workflow = {"stage": "S4", "consent": {"agreed": agreed, "total": len(owners), "threshold": 1.0}, "input_hash": ih}
inputs = {"mgmt_fee": 18000.0, "profit_impl": 9000.0, "advance": 60000.0, "operating": 3000.0,
          "我方收入": 6000.0, "我方投入": 1200.0, "deadline_proximity": 0.4, "p_haircut": 0.9}
dec = D.decide(result, workflow, inputs)
ok, errs = D.validate_decision(dec)
assert ok, errs
sys.stdout.write(json.dumps(dec, ensure_ascii=False))
`;
const decision = JSON.parse(execFileSync('python3', ['-c', py], { cwd: ROOT, encoding: 'utf8' }));

// ── 2) WORKLOGIC → wf / snap ──
const wsHtml = readFileSync(join(ROOT, 'apps/web/workspace.html'), 'utf8');
const mm = wsHtml.match(/\/\*WORKLOGIC-BEGIN\*\/([\s\S]*?)\/\*WORKLOGIC-END\*\//);
if (!mm) throw new Error('workspace.html 找不到 WORKLOGIC 區塊');
const WORKLOGIC = eval(mm[1] + '\nWORKLOGIC');
const wf = WORKLOGIC.importV21ToWorkflow(v21);
const snap = WORKLOGIC.displaySnapshot(v21);
const pid = wf.project.project_id;

// 可溯源鐵律：decision.input_hash 必須配得上 demo 快照
if (!WORKLOGIC.matchDecision(wf, decision)) throw new Error('decision input_hash 對不上 demo 快照');

// ── 3) 寫出 ──
const banner =
`/* apps/web/demo-case.js — B1.5 零步啟動：合成示範案（案例D，schema v2.1）預載記錄。
   AUTO-GENERATED by tools/build_demo_case.mjs — 勿手改。
   來源＝schemas/examples/v2/v2_1_案例D_權變示範.json（合成、零真實資料）＋ core/redcf decision.decide()。
   wf/snap 由 workspace WORKLOGIC 產出、engine 逐欄自 v2.1、decision 由決策引擎產出並經 schema 驗證。
   零公式、零推論——駕駛艙據此在無匯入時即有可操作案件（空狀態＝可運作狀態）。 */
`;
const rec = { pid, wf, snap, engine: v21.engine, decision };
writeFileSync(join(ROOT, 'apps/web/demo-case.js'), banner + 'self.DEMO_CASE = ' + JSON.stringify(rec, null, 1) + ';\n');
console.log(`✅ demo-case.js：pid=${pid} verdict=${decision.verdict} scr=${snap.shared_cost_ratio} rr=${snap.return_rate}`);
