# -*- coding: utf-8 -*-
"""Build the static chart-contract registry bundle used by apps/web."""
import json
import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "apps" / "web" / "chart-contracts.json"
BUNDLE_PATH = ROOT / "apps" / "web" / "chart-contracts.js"


def render_bundle(registry: dict) -> str:
    payload = json.dumps(registry, ensure_ascii=False, separators=(",", ":"))
    return f'''/* GENERATED by tools/build_chart_contracts.py; edit chart-contracts.json. */
(function (root) {{
  "use strict";
  var registry = {payload};
  var api = {{
    schema_version: registry.schema_version,
    all: registry.charts,
    get: function (chartId) {{
      for (var i = 0; i < registry.charts.length; i++) {{
        if (registry.charts[i].chart_id === chartId) return registry.charts[i];
      }}
      return null;
    }}
  }};
  root.ChartContracts = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
}})(typeof self !== "undefined" ? self : this);
'''


def main() -> int:
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    BUNDLE_PATH.write_text(render_bundle(registry), encoding="utf-8", newline="\n")
    print(f"built {BUNDLE_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
